### ISSUE TITLE
ArchLinuxJPの名刺について

### ISSUE THREAD

**Issue by syui** [ArchLinuxJP/archimg-jp#2]
## 提案

CSSやJSで作成した名刺のテンプレートページから、入力されたTwitterやGitHubのユーザー情報に基づいて名刺を自動生成するものがあったりすると便利そう。

## 内容

@takeyari さんが名刺を作成してくれました。現在、名刺に関しては、以下の様なものがあります。

- http://vimcard.herokuapp.com/

- https://github.com/kobake/metro-css-card/

まず一つ目は、Herokuでユーザー情報に基づいた名刺を作成してダウンロードできる形式です。もう一つは、JSとCSSによる名刺ページを作成します。

したがって、CSSやJSで作成した名刺のテンプレートページから入力されたTwitterやGitHubのユーザー情報から、名刺(ユーザーアイコン付き)を自動生成するものがあったりすると手軽で便利そうだと思いました。

## サンプル

ここで、一つのサンプルを作成してみました。

![](https://raw.githubusercontent.com/ArchLinuxJP/archimg-jp/master/visiting-card/archlinuxjp_visicard_sample.png)

一応、使用したツールを挙げておきます。

- http://somestuff.ru/filter/HTML5/I

> 一部、ArchLinuxJPとの区切りを明確にする波を表現するため、ポリゴン生成に使用しました 

- https://convertio.co/ja/svg-png/

> .svgを.pngに変換するために使用しました

下部分は、テンプレートとして利用する感じで、上部分にユーザー情報に基づいたプレビューなどをGitHub APIなどを使って処理する感じです。

GitHubやTwitterなどのユーザー情報入力があった場合、アイコンはWebフォントを使って表現し、名刺全体をWebページ形式で作成する感じが良いのではないかと思います。

これは、画像処理の過程で面倒になったので、サンプルには表示していません。が、位置は大体、URLの下辺りになると思われます。

**Comment by takeyari** [comment]
確かに自動で生成できるとメンバーで統一した名刺が作れて便利ですね。何より楽ですし。
名刺を生成するサービス作ってみます？

**Comment by syui** [comment]
@takeyari そうですね。そっちの方向で検討してみましょうか。

まずは、とてもシンプルなことからはじめる感じで。

**Comment by syui** [comment]
名刺に関しては、こちらのリポジトリでテストすることにします。

https://github.com/ArchLinuxJP/archcard-jp
